USE medical_db;

DROP TABLE IF EXISTS medical_data;
CREATE TABLE medical_data (
    Hospital_Service_Area VARCHAR(50),
    Hospital_County VARCHAR(50),
    Operating_Certificate_Number VARCHAR(30),
    Permanent_Facility_Id VARCHAR(20),
    Facility_Name VARCHAR(200),
    Age_Group VARCHAR(20),
    Zip_Code_3digits VARCHAR(5),
    Gender VARCHAR(10),
    Race VARCHAR(50),
    Ethnicity VARCHAR(50),
    Length_of_Stay INT,
    Type_of_Admission VARCHAR(50),
    Patient_Disposition VARCHAR(100),
    Discharge_Year INT,
    CCSR_Diagnosis_Code VARCHAR(10),
    CCSR_Diagnosis_Description VARCHAR(255),
    CCSR_Procedure_Code VARCHAR(10),
    CCSR_Procedure_Description VARCHAR(255),
    APR_DRG_Code INT,
    APR_DRG_Description VARCHAR(255),
    APR_MDC_Code INT,
    APR_MDC_Description VARCHAR(255),
    APR_Severity_of_Illness_Code INT,
    APR_Severity_of_Illness_Description VARCHAR(30),
    APR_Risk_of_Mortality VARCHAR(20),
    APR_Medical_Surgical_Description VARCHAR(30),
    Payment_Typology_1 VARCHAR(50),
    Payment_Typology_2 VARCHAR(50),
    Payment_Typology_3 VARCHAR(50),
    Birth_Weight INT,
    Emergency_Department_Indicator VARCHAR(5),
    Total_Charges DOUBLE,
    Total_Costs DOUBLE,
    INDEX idx_discharge_year (Discharge_Year),
    INDEX idx_diagnosis (CCSR_Diagnosis_Code),
    INDEX idx_facility (Facility_Name),
    INDEX idx_year_diagnosis (Discharge_Year, CCSR_Diagnosis_Code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
